# Generated by Django 5.0.3 on 2024-03-19 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_alter_photo_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="myapp.category",
            ),
        ),
    ]
